#include "images.h"

// Image data generated by LVGL Image Converter
const lv_img_dsc_t imagen_ejemplo = {
//   .header.always_zero = 0,
//   .header.w = 64,
//   .header.h = 64,
//   .data_size = 64 * 64 * LV_COLOR_DEPTH / 8,
//   .header.cf = LV_IMG_CF_TRUE_COLOR,
//   .data = imagen_ejemplo_map
};